#!/bin/bash
# .bash_profile
#
# bash_profile and or /etc/profile, /etc/profile.d/ are only
# normally read on "login" shells
#
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs


